apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rollup.name" . }}-geth
  labels:
    app: {{ include "rollup.appName" . }}
  namespace: {{ include "rollup.namespace" . }}
spec:
  replicas : {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rollup.appName" . }}
  template:
    metadata:
      name: {{ include "rollup.name" . }}-execution-chain
      labels:
        app: {{ include "rollup.appName" . }}
    spec:
      initContainers:
        {{- if .Values.config.geth.purgeMempool }}
        - name: purge-mempool
          image: {{ include "rollup.image" . }}
          command: [ "sh", "-c", "rm" ]
          args:
            - -f
            - {{ include "rollup.gethDataDir" . }}/geth/transactions.rlp
          volumeMounts:
            - mountPath: /home/geth
              name: {{ include "rollup.name" $ }}-rollup-shared-storage-vol
              subPath: {{ include "rollup.name" . }}/executor
        {{- end }}
        - name: init-geth
          command: [ "/scripts/init-geth.sh" ]
          image: {{ include "rollup.image" . }}
          envFrom:
            - configMapRef:
                name: {{ include "rollup.name" . }}-geth-env
          volumeMounts:
            - mountPath: /scripts/
              name: {{ include "rollup.name" . }}-executor-scripts-volume
            - mountPath: /home/geth
              name: {{ include "rollup.name" $ }}-rollup-shared-storage-vol
              subPath: {{ include "rollup.name" . }}/executor
      containers:
        - name: geth
          command: [ "geth" ]
          args:
            - --datadir=$(data_dir)/
            - --networkid={{ .Values.config.rollup.networkId }}
            - --http
            - --http.addr=0.0.0.0
            - --http.port={{ .Values.ports.jsonRPC }}
            - --http.corsdomain=*
            - --http.vhosts=*
            - --http.api=eth,net,web3,debug,txpool
            - --ws
            - --ws.addr=0.0.0.0
            - --ws.port={{ .Values.ports.wsRPC }}
            - --ws.origins=*
            - --grpc
            - --grpc.addr=0.0.0.0
            - --grpc.port={{ .Values.ports.executionGRPC }}
            - --db.engine={{ .Values.config.rollup.dbEngine }}
            - --maxpeers=0
            {{- if .Values.config.rollup.archiveNode }}
            - --gcmode=archive
            - --state.scheme=hash
            - --history.transactions=0
            - --history.state=0
            {{- else }}
            - --state.scheme=path
            - --history.state=540000
            {{- end }}
            {{- end }}
          image: {{ include "rollup.image" . }}
          volumeMounts:
            - mountPath: /scripts/
              name: {{ include "rollup.name" . }}-executor-scripts-volume
              readOnly: true
            - mountPath: /home/geth
              name: {{ include "rollup.name" . }}-rollup-shared-storage-vol
              subPath: {{ include "rollup.name" . }}/executor
          ports:
            - containerPort: {{ .Values.ports.jsonRPC }}
              name: json-rpc
            - containerPort: {{ .Values.ports.wsRPC }}
              name: ws-rpc
            - containerPort: {{ .Values.ports.executionGRPC }}
              name: execution-grpc
            {{- if .Values.metrics.enabled }}
            - containerPort: {{ .Values.ports.metrics }}
              name: geth-metr
            {{- end }}
          resources:
            {{- toYaml .Values.resources.geth | trim | nindent 12 }}
        - name: composer
          image: {{ include "composer.image" . }}
          command: [ "/usr/local/bin/astria-composer" ]
          stdin: {{ .Values.global.useTTY }}
          tty: {{ .Values.global.useTTY }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.rollup.name }}-composer-env
          volumeMounts:
          - mountPath: "/var/secrets"
            name: sequencer-private-key
          startupProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.ports.composerHealthAPI }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.ports.composerHealthAPI }}
          ports:
            {{- if .Values.config.rollup.metrics.enabled }}
            - containerPort: {{ .Values.ports.composerMetrics }}
              name: composer-metr
            {{- end }}
            - containerPort: {{ .Values.ports.composerHealthAPI }}
              name: composer-api
          resources:
            {{- toYaml .Values.resources.composer | trim | nindent 12 }}
        - name: conductor
          image: {{ include "conductor.image" . }}
          command: [ "/usr/local/bin/astria-conductor" ]
          stdin: {{ .Values.global.useTTY }}
          tty: {{ .Values.global.useTTY }}
          envFrom:
            - configMapRef:
                name: {{ include "rollup.name" . }}-conductor-env
          resources:
            {{- toYaml .Values.resources.conductor | trim | nindent 12 }}
          {{- if .Values.metrics.enabled }}
          ports:
            - containerPort: {{ .Values.ports.conductorMetrics }}
              name: conductor-metr
          {{- end }}
      volumes:
        - name: {{ include "rollup.name" . }}-executor-scripts-volume
          configMap:
            name: {{ include "rollup.name" . }}-executor-scripts
            defaultMode: 0500
        - name: {{ include "rollup.name" $ }}-rollup-shared-storage-vol
          {{- if .Values.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "rollup.name" $ }}-rollup-shared-storage-pvc-geth
          {{- else }}
          emptyDir: {}
          {{- end }}
---
