apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.moniker }}-sequencer-upgrades
  namespace: {{ include "sequencer.namespace" . }}
data:
  upgrades.json: |
    {{- tpl (.Files.Get "files/upgrades/upgrades.json") $ | nindent 4 }}
